// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSKPLmyQb-b8gfsShLSzbMBPQ10cHqNdc',
    appId: '1:350176906989:android:b7d8433bdfa0641ca406e4',
    messagingSenderId: '350176906989',
    projectId: 'monitoring-system-f50e6',
    storageBucket: 'monitoring-system-f50e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSKPLmyQb-b8gfsShLSzbMBPQ10cHqNdc',
    appId: '1:350176906989:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '350176906989',
    projectId: 'monitoring-system-f50e6',
    storageBucket: 'monitoring-system-f50e6.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSKPLmyQb-b8gfsShLSzbMBPQ10cHqNdc',
    appId: '1:350176906989:web:b7d8433bdfa0641ca406e4',
    messagingSenderId: '350176906989',
    projectId: 'monitoring-system-f50e6',
    storageBucket: 'monitoring-system-f50e6.firebasestorage.app',
    authDomain: 'monitoring-system-f50e6.firebaseapp.com',
  );
}
